name: Testing stuff

on:
  push:
    branches:
      - master
      - eventtest

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ contains("#skip", join(github.event.commits.*.message, ' ')) }}
        run: echo "$COMMIT_MESSAGES"
